In [17]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Shiva teja\Downloads\Burnout_Risk_Retention_Analysis\Dataset\mental_health_burnout_tech_2026.csv")

df.head()

,employee_id,age,gender,country,job_role,seniority_level,years_experience,years_at_company,company_size,industry,...,autonomy_score,stress_score,burnout_score,phq9_score,phq9_category,gad7_score,gad7_category,burnout_level,seeks_mental_health_support,job_change_intention
0,1,33,Male,India,Software Engineer,Lead,11,6.4,Small (51-200),Healthcare Tech,...,6.1,10.0,10.0,19,Moderately Severe (15-19),12,Moderate (10-14),Severe,1,1
1,2,24,Non-binary,USA,Full Stack Developer,Manager,0,5.7,Startup (1-50),Fintech,...,5.4,9.3,7.0,8,Mild (5-9),6,Mild (5-9),High,1,1
2,3,36,Prefer not to say,USA,Software Engineer,Lead,14,5.6,Mid (201-1000),Fintech,...,4.1,8.9,8.5,8,Mild (5-9),9,Mild (5-9),Severe,0,1
3,4,38,Non-binary,USA,Software Engineer,Lead,14,1.2,Mid (201-1000),SaaS / Cloud,...,7.3,10.0,10.0,14,Moderate (10-14),11,Moderate (10-14),Severe,0,1
4,5,22,Non-binary,France,ML Engineer,Junior,0,3.0,Small (51-200),AI / ML Startup,...,4.4,7.7,5.4,8,Mild (5-9),0,Minimal (0-4),Moderate,1,0

In [20]:
df.shape

(100000, 36)

In [21]:
df.columns

Index(['employee_id', 'age', 'gender', 'country', 'job_role',
       'seniority_level', 'years_experience', 'years_at_company',
       'company_size', 'industry', 'work_mode', 'salary_usd',
       'work_hours_per_week', 'meetings_per_day', 'team_size',
       'sleep_hours_per_night', 'exercise_days_per_week',
       'vacation_days_taken', 'therapy_access', 'uses_therapy',
       'ai_tools_daily', 'manager_support_score', 'work_life_balance_score',
       'job_satisfaction_score', 'social_support_score',
       'deadline_pressure_score', 'autonomy_score', 'stress_score',
       'burnout_score', 'phq9_score', 'phq9_category', 'gad7_score',
       'gad7_category', 'burnout_level', 'seeks_mental_health_support',
       'job_change_intention'],
      dtype='object')

In [22]:
df.columns.tolist()

['employee_id',
 'age',
 'gender',
 'country',
 'job_role',
 'seniority_level',
 'years_experience',
 'years_at_company',
 'company_size',
 'industry',
 'work_mode',
 'salary_usd',
 'work_hours_per_week',
 'meetings_per_day',
 'team_size',
 'sleep_hours_per_night',
 'exercise_days_per_week',
 'vacation_days_taken',
 'therapy_access',
 'uses_therapy',
 'ai_tools_daily',
 'manager_support_score',
 'work_life_balance_score',
 'job_satisfaction_score',
 'social_support_score',
 'deadline_pressure_score',
 'autonomy_score',
 'stress_score',
 'burnout_score',
 'phq9_score',
 'phq9_category',
 'gad7_score',
 'gad7_category',
 'burnout_level',
 'seeks_mental_health_support',
 'job_change_intention']

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 36 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   employee_id                  100000 non-null  int64
 1   age                          100000 non-null  int64
 2   gender                       100000 non-null  object
 3   country                      100000 non-null  object
 4   job_role                     100000 non-null  object
 5   seniority_level              100000 non-null  object
 6   years_experience             100000 non-null  int64
 7   years_at_company             100000 non-null  float64
 8   company_size                 100000 non-null  object
 9   industry                     100000 non-null  object
 10  work_mode                    100000 non-null  object
 11  salary_usd                   100000 non-null  int64
 12  work_hours_per_week          100000 non-null  int64
 13  meetings_per_day             100000 non-null  float64
 14  team_size                    100000 non-null  int64
 15  sleep_hours_per_night        100000 non-null  float64
 16  exercise_days_per_week       100000 non-null  int64
 17  vacation_days_taken          100000 non-null  int64
 18  therapy_access               100000 non-null  int64
 19  uses_therapy                 100000 non-null  int64
 20  ai_tools_daily               100000 non-null  int64
 21  manager_support_score        100000 non-null  float64
 22  work_life_balance_score      100000 non-null  float64
 23  job_satisfaction_score       100000 non-null  float64
 24  social_support_score         100000 non-null  float64
 25  deadline_pressure_score      100000 non-null  float64
 26  autonomy_score               100000 non-null  float64
 27  stress_score                 100000 non-null  float64
 28  burnout_score                100000 non-null  float64
 29  phq9_score                   100000 non-null  int64
 30  phq9_category                100000 non-null  object
 31  gad7_score                   100000 non-null  int64
 32  gad7_category                100000 non-null  object
 33  burnout_level                100000 non-null  object
 34  seeks_mental_health_support  100000 non-null  int64
 35  job_change_intention         100000 non-null  int64
dtypes: float64(11), int64(15), object(10)
memory usage: 27.5+ MB

In [24]:
df.isnull().sum()

employee_id                    0
age                            0
gender                         0
country                        0
job_role                       0
seniority_level                0
years_experience               0
years_at_company               0
company_size                   0
industry                       0
work_mode                      0
salary_usd                     0
work_hours_per_week            0
meetings_per_day               0
team_size                      0
sleep_hours_per_night          0
exercise_days_per_week         0
vacation_days_taken            0
therapy_access                 0
uses_therapy                   0
ai_tools_daily                 0
manager_support_score          0
work_life_balance_score        0
job_satisfaction_score         0
social_support_score           0
deadline_pressure_score        0
autonomy_score                 0
stress_score                   0
burnout_score                  0
phq9_score                     0
phq9_category                  0
gad7_score                     0
gad7_category                  0
burnout_level                  0
seeks_mental_health_support    0
job_change_intention           0
dtype: int64

In [27]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.describe()

,employee_id,age,years_experience,years_at_company,salary_usd,work_hours_per_week,meetings_per_day,team_size,sleep_hours_per_night,exercise_days_per_week,...,job_satisfaction_score,social_support_score,deadline_pressure_score,autonomy_score,stress_score,burnout_score,phq9_score,gad7_score,seeks_mental_health_support,job_change_intention
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000
mean,50000.500000,31.305670,9.343690,2.492581,83285.490230,47.104080,4.162244,18.009650,6.102392,2.968730,...,4.834823,5.383951,6.385095,5.836528,7.055399,5.401675,6.27194,5.118920,0.497890,0.320020
std,28867.657797,6.427924,6.401543,2.450426,39392.584827,5.246902,1.937849,12.607473,0.998808,1.772762,...,1.920796,1.832774,1.769242,1.836491,2.128530,2.668425,4.95427,4.007513,0.499998,0.466486
min,1.000000,22.000000,0.000000,0.100000,40000.000000,35.000000,0.000000,2.000000,3.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,25000.750000,26.000000,4.000000,0.700000,46018.250000,44.000000,2.800000,8.000000,5.400000,2.000000,...,3.500000,4.100000,5.200000,4.600000,5.500000,3.500000,2.00000,2.000000,0.000000,0.000000
50%,50000.500000,31.000000,9.000000,1.700000,76630.500000,47.000000,4.000000,16.000000,6.100000,3.000000,...,4.800000,5.400000,6.400000,5.800000,7.100000,5.400000,6.00000,5.000000,0.000000,0.000000
75%,75000.250000,36.000000,14.000000,3.500000,109113.000000,51.000000,5.400000,25.000000,6.800000,4.000000,...,6.200000,6.600000,7.600000,7.100000,8.900000,7.400000,10.00000,8.000000,1.000000,1.000000
max,100000.000000,55.000000,25.000000,15.000000,267961.000000,72.000000,12.000000,59.000000,10.000000,7.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,27.00000,21.000000,1.000000,1.000000

In [28]:
df["company_size"].unique()

array(['Small (51-200)', 'Startup (1-50)', 'Mid (201-1000)',
       'Large (1001-5000)', 'Enterprise (5000+)'], dtype=object)

In [29]:
df["industry"].unique()

array(['Healthcare Tech', 'Fintech', 'SaaS / Cloud', 'AI / ML Startup',
       'Social Media / AdTech', 'Consulting', 'Cybersecurity',
       'E-commerce', 'Gaming', 'Enterprise Software'], dtype=object)

In [30]:
df["therapy_access"].unique()

array([0, 1])

In [31]:
df["job_change_intention"].unique()

array([1, 0])

In [32]:
df["burnout_level"].unique()

array(['Severe', 'High', 'Moderate', 'Low'], dtype=object)

In [33]:
df["company_size"].value_counts()

company_size
Mid (201-1000)        25062
Large (1001-5000)     22027
Startup (1-50)        19771
Small (51-200)        18067
Enterprise (5000+)    15073
Name: count, dtype: int64

In [34]:
df["industry"].value_counts()

industry
SaaS / Cloud             19957
Fintech                  15064
E-commerce               12057
AI / ML Startup          11957
Healthcare Tech          10004
Cybersecurity             7900
Consulting                7012
Enterprise Software       6098
Gaming                    5936
Social Media / AdTech     4015
Name: count, dtype: int64

In [35]:
df["therapy_access"].value_counts()

therapy_access
0    65938
1    34062
Name: count, dtype: int64

In [36]:
df["burnout_level"].value_counts()

burnout_level
Severe      28576
Moderate    26255
Low         25807
High        19362
Name: count, dtype: int64

In [37]:
df["job_change_intention"].value_counts()

job_change_intention
0    67998
1    32002
Name: count, dtype: int64

In [38]:
burnout_by_company = (
    df.groupby(["company_size", "industry"])["burnout_score"]
      .mean()
      .reset_index()
      .sort_values(by="burnout_score", ascending=False)
)

burnout_by_company.head(10)

          company_size         industry  burnout_score
35      Small (51-200)          Fintech       5.664398
20      Mid (201-1000)  AI / ML Startup       5.618779
0   Enterprise (5000+)  AI / ML Startup       5.612150
36      Small (51-200)           Gaming       5.607333
40      Startup (1-50)  AI / ML Startup       5.594442
15   Large (1001-5000)          Fintech       5.589483
45      Startup (1-50)          Fintech       5.569760
10   Large (1001-5000)  AI / ML Startup       5.569689
6   Enterprise (5000+)           Gaming       5.565974
30      Small (51-200)  AI / ML Startup       5.559807

In [6]:
burnout_jobrole = (
    df.groupby("job_role")["burnout_score"]
      .mean()
      .sort_values(ascending=False)
      .reset_index()
)

burnout_jobrole

                  job_role  burnout_score
0          Product Manager       5.446679
1        Backend Developer       5.444785
2       Frontend Developer       5.422208
3              ML Engineer       5.415602
4              QA Engineer       5.405471
5   Cybersecurity Engineer       5.400100
6           Data Scientist       5.399900
7          DevOps Engineer       5.394666
8        Software Engineer       5.387779
9           Cloud Engineer       5.380904
10            Data Analyst       5.370391
11    Full Stack Developer       5.354727

In [5]:
df = pd.read_csv(r"C:\Users\Shiva teja\Downloads\Burnout_Risk_Retention_Analysis\Dataset\mental_health_burnout_tech_2026.csv")

In [4]:
import pandas as pd
import numpy as np

In [7]:
burnout_workmode = (
    df.groupby("work_mode")["burnout_score"]
      .mean()
      .sort_values(ascending=False)
      .reset_index()
)

burnout_workmode

  work_mode  burnout_score
0    Remote       5.478684
1    Hybrid       5.432482
2   On-site       5.246239

In [8]:
burnout_seniority = (
    df.groupby("seniority_level")["burnout_score"]
      .mean()
      .sort_values(ascending=False)
      .reset_index()
)

burnout_seniority

  seniority_level  burnout_score
0         Manager       7.439909
1            Lead       7.434381
2       Principal       5.529300
3          Junior       4.802427
4          Senior       4.790681
5             Mid       4.768614

In [9]:
top10_profiles = (
    df.groupby(["company_size", "industry"])["burnout_score"]
      .mean()
      .sort_values(ascending=False)
      .head(10)
      .reset_index()
)

top10_profiles

         company_size         industry  burnout_score
0      Small (51-200)          Fintech       5.664398
1      Mid (201-1000)  AI / ML Startup       5.618779
2  Enterprise (5000+)  AI / ML Startup       5.612150
3      Small (51-200)           Gaming       5.607333
4      Startup (1-50)  AI / ML Startup       5.594442
5   Large (1001-5000)          Fintech       5.589483
6      Startup (1-50)          Fintech       5.569760
7   Large (1001-5000)  AI / ML Startup       5.569689
8  Enterprise (5000+)           Gaming       5.565974
9      Small (51-200)  AI / ML Startup       5.559807

In [10]:
burnout_country = (
    df.groupby("country")["burnout_score"]
      .mean()
      .sort_values(ascending=False)
      .reset_index()
)

burnout_country.head(10)

       country  burnout_score
0       France       5.430756
1    Australia       5.430524
2      Germany       5.425581
3           UK       5.423302
4          USA       5.415532
5       Canada       5.393136
6  Netherlands       5.378134
7        India       5.374711
8    Singapore       5.367114
9       Brazil       5.352173

In [11]:
corr_columns = [
    "burnout_score",
    "stress_score",
    "work_life_balance_score",
    "manager_support_score",
    "job_satisfaction_score",
    "deadline_pressure_score",
    "autonomy_score",
    "sleep_hours_per_night",
    "exercise_days_per_week",
    "work_hours_per_week",
    "meetings_per_day",
    "years_at_company",
    "salary_usd",
    "phq9_score",
    "gad7_score"
]

burnout_corr = (
    df[corr_columns]
    .corr()["burnout_score"]
    .sort_values(ascending=False)
)

print(burnout_corr)

burnout_score              1.000000
stress_score               0.853803
gad7_score                 0.716728
phq9_score                 0.716383
work_hours_per_week        0.474050
meetings_per_day           0.455603
salary_usd                 0.162126
deadline_pressure_score    0.142685
job_satisfaction_score     0.056128
work_life_balance_score    0.000702
years_at_company          -0.001618
autonomy_score            -0.084505
manager_support_score     -0.168501
exercise_days_per_week    -0.206069
sleep_hours_per_night     -0.338268
Name: burnout_score, dtype: float64

In [12]:

driver_ranking = burnout_corr.drop("burnout_score")


driver_ranking = driver_ranking.reset_index()
driver_ranking.columns = ["Factor", "Correlation"]


driver_ranking["Absolute_Correlation"] = driver_ranking["Correlation"].abs()


driver_ranking = driver_ranking.sort_values(
    by="Absolute_Correlation",
    ascending=False
)

driver_ranking

                     Factor  Correlation  Absolute_Correlation
0              stress_score     0.853803              0.853803
1                gad7_score     0.716728              0.716728
2                phq9_score     0.716383              0.716383
3       work_hours_per_week     0.474050              0.474050
4          meetings_per_day     0.455603              0.455603
13    sleep_hours_per_night    -0.338268              0.338268
12   exercise_days_per_week    -0.206069              0.206069
11    manager_support_score    -0.168501              0.168501
5                salary_usd     0.162126              0.162126
6   deadline_pressure_score     0.142685              0.142685
10           autonomy_score    -0.084505              0.084505
7    job_satisfaction_score     0.056128              0.056128
9          years_at_company    -0.001618              0.001618
8   work_life_balance_score     0.000702              0.000702

In [13]:
def relationship(x):
    if x > 0:
        return "Positive Association"
    else:
        return "Negative Association"

driver_ranking["Association"] = driver_ranking["Correlation"].apply(relationship)

driver_ranking

,Factor,Correlation,Absolute_Correlation,Association
0,stress_score,0.853803,0.853803,Positive Association
1,gad7_score,0.716728,0.716728,Positive Association
2,phq9_score,0.716383,0.716383,Positive Association
3,work_hours_per_week,0.474050,0.474050,Positive Association
4,meetings_per_day,0.455603,0.455603,Positive Association
13,sleep_hours_per_night,-0.338268,0.338268,Negative Association
12,exercise_days_per_week,-0.206069,0.206069,Negative Association
11,manager_support_score,-0.168501,0.168501,Negative Association
5,salary_usd,0.162126,0.162126,Positive Association
6,deadline_pressure_score,0.142685,0.142685,Positive Association
10,autonomy_score,-0.084505,0.084505,Negative Association
7,job_satisfaction_score,0.056128,0.056128,Positive Association
9,years_at_company,-0.001618,0.001618,Negative Association
8,work_life_balance_score,0.000702,0.000702,Positive Association

In [14]:
therapy_access_burnout = (
    df.groupby("therapy_access")["burnout_score"]
      .agg(["mean", "count"])
      .reset_index()
)

therapy_access_burnout["therapy_access"] = therapy_access_burnout["therapy_access"].map({
    0: "No Access",
    1: "Has Access"
})

therapy_access_burnout

  therapy_access      mean  count
0      No Access  5.470281  65938
1     Has Access  5.268866  34062

In [15]:
therapy_access_phq = (
    df.groupby("therapy_access")["phq9_score"]
      .agg(["mean", "count"])
      .reset_index()
)

therapy_access_phq["therapy_access"] = therapy_access_phq["therapy_access"].map({
    0: "No Access",
    1: "Has Access"
})

therapy_access_phq

  therapy_access      mean  count
0      No Access  6.575344  65938
1     Has Access  5.684605  34062

In [16]:
therapy_usage_burnout = (
    df.groupby("uses_therapy")["burnout_score"]
      .agg(["mean", "count"])
      .reset_index()
)

therapy_usage_burnout["uses_therapy"] = therapy_usage_burnout["uses_therapy"].map({
    0: "Doesn't Use Therapy",
    1: "Uses Therapy"
})

therapy_usage_burnout

          uses_therapy      mean  count
0  Doesn't Use Therapy  5.464733  84815
1         Uses Therapy  5.049470  15185

In [17]:
therapy_usage_gad = (
    df.groupby("uses_therapy")["gad7_score"]
      .agg(["mean", "count"])
      .reset_index()
)

therapy_usage_gad["uses_therapy"] = therapy_usage_gad["uses_therapy"].map({
    0: "Doesn't Use Therapy",
    1: "Uses Therapy"
})

therapy_usage_gad

          uses_therapy      mean  count
0  Doesn't Use Therapy  5.357012  84815
1         Uses Therapy  3.789068  15185

In [18]:
therapy_usage_phq = (
    df.groupby("uses_therapy")["phq9_score"]
      .agg(["mean", "count"])
      .reset_index()
)

therapy_usage_phq["uses_therapy"] = therapy_usage_phq["uses_therapy"].map({
    0: "Doesn't Use Therapy",
    1: "Uses Therapy"
})

therapy_usage_phq

          uses_therapy      mean  count
0  Doesn't Use Therapy  6.563238  84815
1         Uses Therapy  4.644913  15185

In [19]:
therapy_summary = pd.DataFrame({
    "Metric": [
        "Therapy Access Rate (%)",
        "Therapy Usage Rate (%)"
    ],
    "Value": [
        df["therapy_access"].mean() * 100,
        df["uses_therapy"].mean() * 100
    ]
})

therapy_summary

                    Metric   Value
0  Therapy Access Rate (%)  34.062
1   Therapy Usage Rate (%)  15.185

In [20]:
flight_risk = df[
    (df["burnout_level"].isin(["High", "Severe"])) &
    (df["job_change_intention"] == 1)
]

print("Flight Risk Employees:", len(flight_risk))

flight_risk.head()

Flight Risk Employees: 20226

,employee_id,age,gender,country,job_role,seniority_level,years_experience,years_at_company,company_size,industry,...,autonomy_score,stress_score,burnout_score,phq9_score,phq9_category,gad7_score,gad7_category,burnout_level,seeks_mental_health_support,job_change_intention
0,1,33,Male,India,Software Engineer,Lead,11,6.4,Small (51-200),Healthcare Tech,...,6.1,10.0,10.0,19,Moderately Severe (15-19),12,Moderate (10-14),Severe,1,1
1,2,24,Non-binary,USA,Full Stack Developer,Manager,0,5.7,Startup (1-50),Fintech,...,5.4,9.3,7.0,8,Mild (5-9),6,Mild (5-9),High,1,1
2,3,36,Prefer not to say,USA,Software Engineer,Lead,14,5.6,Mid (201-1000),Fintech,...,4.1,8.9,8.5,8,Mild (5-9),9,Mild (5-9),Severe,0,1
3,4,38,Non-binary,USA,Software Engineer,Lead,14,1.2,Mid (201-1000),SaaS / Cloud,...,7.3,10.0,10.0,14,Moderate (10-14),11,Moderate (10-14),Severe,0,1
5,6,22,Female,Brazil,Data Analyst,Principal,0,4.4,Startup (1-50),Social Media / AdTech,...,9.0,7.1,7.4,9,Mild (5-9),7,Mild (5-9),Severe,0,1

In [21]:
silent_burnout = df[
    (df["burnout_level"].isin(["High", "Severe"])) &
    (df["job_change_intention"] == 0)
]

print("Silent Burnout Employees:", len(silent_burnout))

silent_burnout.head()

Silent Burnout Employees: 27712

,employee_id,age,gender,country,job_role,seniority_level,years_experience,years_at_company,company_size,industry,...,autonomy_score,stress_score,burnout_score,phq9_score,phq9_category,gad7_score,gad7_category,burnout_level,seeks_mental_health_support,job_change_intention
10,11,37,Female,USA,Data Analyst,Lead,15,1.4,Mid (201-1000),AI / ML Startup,...,6.3,10.0,10.0,13,Moderate (10-14),11,Moderate (10-14),Severe,1,0
11,12,36,Male,UK,Product Manager,Lead,16,1.4,Startup (1-50),Cybersecurity,...,6.8,6.8,6.0,3,None (0-4),0,Minimal (0-4),High,1,0
14,15,34,Female,India,Software Engineer,Manager,10,0.9,Enterprise (5000+),SaaS / Cloud,...,5.0,10.0,10.0,9,Mild (5-9),12,Moderate (10-14),Severe,0,0
18,19,37,Female,India,Data Scientist,Manager,14,0.4,Mid (201-1000),SaaS / Cloud,...,4.0,7.1,6.7,3,None (0-4),0,Minimal (0-4),High,1,0
22,23,40,Female,UK,Product Manager,Mid,16,0.3,Enterprise (5000+),Gaming,...,6.8,6.5,6.3,0,None (0-4),11,Moderate (10-14),High,1,0

In [22]:
healthy_performer = df[
    (df["burnout_level"] == "Low") &
    (df["job_satisfaction_score"] >= 7)
]

print("Healthy Performers:", len(healthy_performer))

healthy_performer.head()

Healthy Performers: 3283

,employee_id,age,gender,country,job_role,seniority_level,years_experience,years_at_company,company_size,industry,...,autonomy_score,stress_score,burnout_score,phq9_score,phq9_category,gad7_score,gad7_category,burnout_level,seeks_mental_health_support,job_change_intention
8,9,31,Male,USA,Software Engineer,Mid,9,1.1,Mid (201-1000),Social Media / AdTech,...,5.2,3.2,2.2,0,None (0-4),0,Minimal (0-4),Low,0,0
61,62,29,Male,France,Data Scientist,Senior,6,1.8,Small (51-200),Fintech,...,7.6,2.5,0.0,0,None (0-4),0,Minimal (0-4),Low,0,0
87,88,31,Female,Australia,Data Analyst,Mid,8,1.1,Mid (201-1000),Fintech,...,2.0,5.0,2.8,0,None (0-4),1,Minimal (0-4),Low,0,0
117,118,31,Male,USA,Backend Developer,Senior,9,0.3,Mid (201-1000),SaaS / Cloud,...,7.2,3.5,2.0,3,None (0-4),4,Minimal (0-4),Low,0,0
235,236,26,Male,Canada,DevOps Engineer,Senior,2,1.0,Startup (1-50),Fintech,...,4.4,6.9,3.4,0,None (0-4),3,Minimal (0-4),Low,1,0

In [23]:
resilient_veteran = df[
    (df["years_at_company"] >= 5) &
    (df["burnout_level"] == "Low")
]

print("Resilient Veterans:", len(resilient_veteran))

resilient_veteran.head()

Resilient Veterans: 3566

,employee_id,age,gender,country,job_role,seniority_level,years_experience,years_at_company,company_size,industry,...,autonomy_score,stress_score,burnout_score,phq9_score,phq9_category,gad7_score,gad7_category,burnout_level,seeks_mental_health_support,job_change_intention
16,17,34,Male,Netherlands,Frontend Developer,Mid,12,5.7,Enterprise (5000+),Social Media / AdTech,...,5.0,7.4,3.4,1,None (0-4),0,Minimal (0-4),Low,1,1
57,58,41,Female,Germany,Data Analyst,Junior,18,7.3,Mid (201-1000),Fintech,...,6.5,7.2,2.2,0,None (0-4),1,Minimal (0-4),Low,0,0
60,61,22,Male,France,DevOps Engineer,Mid,1,9.6,Enterprise (5000+),AI / ML Startup,...,6.1,6.4,1.9,2,None (0-4),6,Mild (5-9),Low,0,0
93,94,30,Female,India,ML Engineer,Mid,9,6.0,Mid (201-1000),SaaS / Cloud,...,6.1,5.0,3.3,3,None (0-4),0,Minimal (0-4),Low,0,0
139,140,51,Male,USA,ML Engineer,Junior,25,5.3,Enterprise (5000+),AI / ML Startup,...,3.4,6.7,3.5,0,None (0-4),6,Mild (5-9),Low,1,0

In [24]:
early_risk = df[
    (df["years_at_company"] < 2) &
    (df["burnout_level"].isin(["High", "Severe"]))
]

print("Early Risk Employees:", len(early_risk))

early_risk.head()

Early Risk Employees: 25948

,employee_id,age,gender,country,job_role,seniority_level,years_experience,years_at_company,company_size,industry,...,autonomy_score,stress_score,burnout_score,phq9_score,phq9_category,gad7_score,gad7_category,burnout_level,seeks_mental_health_support,job_change_intention
3,4,38,Non-binary,USA,Software Engineer,Lead,14,1.2,Mid (201-1000),SaaS / Cloud,...,7.3,10.0,10.0,14,Moderate (10-14),11,Moderate (10-14),Severe,0,1
10,11,37,Female,USA,Data Analyst,Lead,15,1.4,Mid (201-1000),AI / ML Startup,...,6.3,10.0,10.0,13,Moderate (10-14),11,Moderate (10-14),Severe,1,0
11,12,36,Male,UK,Product Manager,Lead,16,1.4,Startup (1-50),Cybersecurity,...,6.8,6.8,6.0,3,None (0-4),0,Minimal (0-4),High,1,0
14,15,34,Female,India,Software Engineer,Manager,10,0.9,Enterprise (5000+),SaaS / Cloud,...,5.0,10.0,10.0,9,Mild (5-9),12,Moderate (10-14),Severe,0,0
18,19,37,Female,India,Data Scientist,Manager,14,0.4,Mid (201-1000),SaaS / Cloud,...,4.0,7.1,6.7,3,None (0-4),0,Minimal (0-4),High,1,0

In [25]:
persona_summary = pd.DataFrame({
    "Persona": [
        "Flight Risk",
        "Silent Burnout",
        "Healthy Performer",
        "Resilient Veteran",
        "Early Risk"
    ],
    "Employees": [
        len(flight_risk),
        len(silent_burnout),
        len(healthy_performer),
        len(resilient_veteran),
        len(early_risk)
    ]
})

persona_summary

             Persona  Employees
0        Flight Risk      20226
1     Silent Burnout      27712
2  Healthy Performer       3283
3  Resilient Veteran       3566
4         Early Risk      25948

In [35]:
df["persona"] = "Other"

# Flight Risk 
df.loc[
    (df["burnout_level"].isin(["High", "Severe"])) &
    (df["job_change_intention"] == 1),
    "persona"
] = "Flight Risk"

# Early Risk
df.loc[
    (df["persona"] == "Other") &
    (df["years_at_company"] < 2) &
    (df["burnout_level"].isin(["High", "Severe"])),
    "persona"
] = "Early Risk"

# Silent Burnout
df.loc[
    (df["persona"] == "Other") &
    (df["burnout_level"].isin(["High", "Severe"])),
    "persona"
] = "Silent Burnout"

# Healthy Performer
df.loc[
    (df["persona"] == "Other") &
    (df["burnout_level"] == "Low") &
    (df["job_satisfaction_score"] >= 7),
    "persona"
] = "Healthy Performer"

# Resilient 
df.loc[
    (df["persona"] == "Other") &
    (df["years_at_company"] >= 5) &
    (df["burnout_level"] == "Low"),
    "persona"
] = "Resilient"

In [27]:
df["persona"].value_counts()

persona
Other                45626
Flight Risk          20226
Early Risk           15012
Silent Burnout       12700
Healthy Performer     3283
Resilient             3153
Name: count, dtype: int64

In [28]:
persona_profile = (
    df.groupby("persona")
      .agg({
          "burnout_score": "mean",
          "stress_score": "mean",
          "manager_support_score": "mean",
          "work_life_balance_score": "mean",
          "sleep_hours_per_night": "mean",
          "work_hours_per_week": "mean",
          "uses_therapy": "mean"
      })
      .round(2)
)

persona_profile["uses_therapy"] = persona_profile["uses_therapy"] * 100
persona_profile.rename(columns={"uses_therapy": "therapy_usage_percent"}, inplace=True)

persona_profile

,burnout_score,stress_score,manager_support_score,work_life_balance_score,sleep_hours_per_night,work_hours_per_week,therapy_usage_percent
persona,,,,,,,
Early Risk,7.55,8.56,5.58,5.41,5.85,49.06,14.0
Flight Risk,7.92,8.76,5.47,5.43,5.79,49.43,13.0
Healthy Performer,1.96,4.65,6.30,5.44,6.53,44.25,18.0
Other,3.47,5.73,6.02,5.42,6.33,45.29,16.0
Resilient,1.99,4.64,6.30,5.44,6.56,44.13,17.0
Silent Burnout,7.53,8.54,5.58,5.44,5.84,49.08,14.0

In [29]:
burnout_paradox = df[
    (df["burnout_level"].isin(["High", "Severe"])) &
    (df["job_satisfaction_score"] >= 7)
]

print("Employees with High Burnout but High Job Satisfaction:")
print(len(burnout_paradox))

Employees with High Burnout but High Job Satisfaction:
7357

In [30]:
burnout_paradox[[
    "burnout_score",
    "stress_score",
    "job_satisfaction_score",
    "work_hours_per_week",
    "sleep_hours_per_night",Em
    "manager_support_score"
]].describe().round(2)

,burnout_score,stress_score,job_satisfaction_score,work_hours_per_week,sleep_hours_per_night,manager_support_score
count,7357.00,7357.00,7357.00,7357.00,7357.00,7357.00
mean,7.83,8.76,7.96,49.70,5.86,5.55
std,1.45,1.27,0.81,4.94,0.98,1.94
min,5.60,3.90,7.00,35.00,3.00,1.00
25%,6.60,7.90,7.30,46.00,5.20,4.20
50%,7.60,9.10,7.70,50.00,5.90,5.60
75%,9.10,10.00,8.40,53.00,6.50,6.90
max,10.00,10.00,10.00,67.00,9.60,10.00

In [32]:
df["sleep_category"] = pd.cut(
    df["sleep_hours_per_night"],
    bins=[0,5,6,7,10],
    labels=[
        "Less than 5 hrs",
        "5-6 hrs",
        "6-7 hrs",
        "More than 7 hrs"
    ]
)

sleep_analysis = (
    df.groupby("sleep_category", observed=False)["burnout_score"]
      .mean()
      .reset_index()
)
sleep_analysis

    sleep_category  burnout_score
0  Less than 5 hrs       6.803294
1          5-6 hrs       5.876087
2          6-7 hrs       5.034121
3  More than 7 hrs       4.032164

In [34]:
df["manager_support_level"] = pd.cut(
    df["manager_support_score"],
    bins=[0,4,7,10],
    labels=[
        "Low Support",
        "Medium Support",
        "High Support"
    ]
)

manager_analysis = (
    df.groupby("manager_support_level",observed=False)["burnout_score"]
      .mean()
      .reset_index()
)

manager_analysis

  manager_support_level  burnout_score
0           Low Support       6.046750
1        Medium Support       5.453489
2          High Support       4.845037

In [36]:
import pandas as pd
import numpy as np

# ---------- PERSONA ----------
df["persona"] = "Other"

# Flight Risk
df.loc[
    (df["burnout_level"].isin(["High", "Severe"])) &
    (df["job_change_intention"] == 1),
    "persona"
] = "Flight Risk"

# Early Risk
df.loc[
    (df["persona"] == "Other") &
    (df["years_at_company"] < 2) &
    (df["burnout_level"].isin(["High", "Severe"])),
    "persona"
] = "Early Risk"

# Silent Burnout
df.loc[
    (df["persona"] == "Other") &
    (df["burnout_level"].isin(["High", "Severe"])),
    "persona"
] = "Silent Burnout"

# Healthy Performer
df.loc[
    (df["persona"] == "Other") &
    (df["burnout_level"] == "Low") &
    (df["job_satisfaction_score"] >= 7),
    "persona"
] = "Healthy Performer"

# Resilient
df.loc[
    (df["persona"] == "Other") &
    (df["years_at_company"] >= 5) &
    (df["burnout_level"] == "Low"),
    "persona"
] = "Resilient"

# Sleep 
df["sleep_category"] = pd.cut(
    df["sleep_hours_per_night"],
    bins=[0, 5, 6, 7, 10],
    labels=[
        "Less than 5 hrs",
        "5-6 hrs",
        "6-7 hrs",
        "More than 7 hrs"
    ]
)

# manager support
df["manager_support_level"] = pd.cut(
    df["manager_support_score"],
    bins=[0, 4, 7, 10],
    labels=[
        "Low Support",
        "Medium Support",
        "High Support"
    ]
)

print(" New columns created successfully!")

 New columns created successfully!

In [37]:
df.columns

Index(['employee_id', 'age', 'gender', 'country', 'job_role',
       'seniority_level', 'years_experience', 'years_at_company',
       'company_size', 'industry', 'work_mode', 'salary_usd',
       'work_hours_per_week', 'meetings_per_day', 'team_size',
       'sleep_hours_per_night', 'exercise_days_per_week',
       'vacation_days_taken', 'therapy_access', 'uses_therapy',
       'ai_tools_daily', 'manager_support_score', 'work_life_balance_score',
       'job_satisfaction_score', 'social_support_score',
       'deadline_pressure_score', 'autonomy_score', 'stress_score',
       'burnout_score', 'phq9_score', 'phq9_category', 'gad7_score',
       'gad7_category', 'burnout_level', 'seeks_mental_health_support',
       'job_change_intention', 'persona', 'sleep_category',
       'manager_support_level'],
      dtype='object')

In [38]:
df.to_csv("burnout_analysis_final.csv", index=False)

print("✅ File saved successfully!")

✅ File saved successfully!

In [39]:
import os

print(os.getcwd())

C:\Users\Shiva teja\Downloads\Burnout_Risk_Retention_Analysis\python